name: Tests

on: push

jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      #push unit test files when done and replace the path in jestArgs
      #with:
        #jestArgs: path/to/my.test.js
